### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Roflincopter** [Roflincopter/dmp#13]
Current version can trigger an "Operation not permitted" in the server when queuing a song. This is most likely a race condition, but I really wanted to commit this first before starting to fix it.

**Comment by NickNick** [comment]
Also got this when trying to add a radio.

**Comment by Roflincopter** [comment]
A possible fix to this is commited in 216364a2b3eae5dfd502e212629f415ba25cbfcc I haven't had it happen for 2 days now but I'm not sure if this has fixed the error. It was neccesary anyway though.

**Comment by Roflincopter** [comment]
This issue hasn't arisen in a few weeks now, closing the issue.
